CREATE DATABASE IF NOT EXISTS EQUIFAX;

USE EQUIFAX;

CREATE TABLE IF NOT EXISTS CAREER (
  CAREER_ID INT(10) NOT NULL AUTO_INCREMENT,
  CAREER VARCHAR(45) NOT NULL,
  PRIMARY KEY (CAREER_ID))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS USER (
  USER_ID INT(10) NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(45) NOT NULL,
  IDEAL_CAREER INT(10),
  PRIMARY KEY (USER_ID),
  CONSTRAINT fk_CAREER
    FOREIGN KEY (IDEAL_CAREER)
    REFERENCES CAREER (CAREER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS QUESTION (
  QUESTION_ID INT(10) NOT NULL AUTO_INCREMENT,
  Q_TEXT VARCHAR(200),
  QUES_Y INT(10),
  QUES_N INT(10),
  CAREER_ID INT(10),
  PRIMARY KEY (QUESTION_ID),
  CONSTRAINT fk_QUESTION_Y
    FOREIGN KEY (QUES_Y)
    REFERENCES QUESTION (QUESTION_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_QUESTION_N
    FOREIGN KEY (QUES_N)
    REFERENCES QUESTION (QUESTION_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_CAREER_ID
    FOREIGN KEY (CAREER_ID)
    REFERENCES CAREER (CAREER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS RESPONSE (
  RESPONSE_ID INT(10) NOT NULL AUTO_INCREMENT,
  RESPONSE_TXT VARCHAR(45),
  USER_ID INT(10),
  QUESTION_ID INT(10),
  PRIMARY KEY (RESPONSE_ID),
  CONSTRAINT fk_USER_ID
    FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT fk_QUESTION_ID
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTION (QUESTION_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




